# Generated by Django 4.2.3 on 2023-07-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctermodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
