# Generated by Django 4.2.3 on 2023-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doctermodel_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctermodel',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
